name: integration_test_preview
description: Integration Test Preview has pre-configured methods that allow for faster test deployment for end to end (e2e) test coverage (using Android and iOS platform UIs).
version: 0.1.1
homepage: https://github.com/the-mac/integration_test_preview

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ^6.0.2

  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter
  
  integration_test_helper: ^0.0.9

  device_preview_community: ^1.0.3

  collection: ^1.15.0

dev_dependencies:

  flutter_lints: ^1.0.0

flutter:
