name: integration_test_preview
description: Integration Test Preview has pre-configured methods that allow for faster test deployment for end to end (e2e) test coverage (using Android and iOS platform UIs).
version: 0.1.3
homepage: https://github.com/the-mac/integration_test_preview

# clear && printf '\e[3J' && dart pub publish --dry-run

# clear && printf '\e[3J' && dart pub publish

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ^6.0.2

  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter
  
  integration_test_helper: ^0.1.0
    # path: ../integration_test_helper

  device_preview: ^1.1.0

  collection: ^1.15.0

dev_dependencies:

  flutter_lints: ^1.0.0
